import argparse
import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

from tqdm import tqdm


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))


DEFAULT_EXTRACTION_FILE = PROJECT_ROOT / "scripts" / "analysis" / "random_entailment_verb_prover_scope_ids_20260505.json"
DEFAULT_CORPUS_PREFIX = "SNLI_SICK_entailment_verb_scope"


def load_dotenv_if_present(dotenv_path: Optional[Path] = None) -> None:
    dotenv_path = dotenv_path or PROJECT_ROOT / ".env"
    if not dotenv_path.exists():
        return
    for raw_line in dotenv_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'\"")
        if key and key not in os.environ:
            os.environ[key] = value


def escape_prolog_string(value: str) -> str:
    return (value or "").replace("\\", "\\\\").replace("'", "\\'")


def prolog_problem_id(value: str) -> str:
    escaped = escape_prolog_string(value)
    return f"'{escaped}'"


def scoped_problem_id(problem: Any) -> str:
    return f"{problem.dataset}:{problem.split}:{problem.id}"


def load_extraction_problems(path: Path, datasets: Sequence[str]) -> List[Any]:
    from kbprojection.loaders.sick import SICKLoader
    from kbprojection.loaders.snli import SNLILoader

    payload = json.loads(path.read_text(encoding="utf-8"))
    loaders = {
        "snli": SNLILoader(),
        "sick": SICKLoader(),
    }
    splits_by_dataset: Dict[str, set[str]] = {dataset: set() for dataset in datasets}
    for dataset in datasets:
        for item in payload.get(dataset, []):
            if item.get("prover_execution_mode") == "easyccg_raw_text_fallback":
                splits_by_dataset[dataset].add(item["split"])
    for dataset, splits in splits_by_dataset.items():
        if splits:
            loaders[dataset].load(splits=sorted(splits))

    problems = []
    for dataset in datasets:
        for item in payload.get(dataset, []):
            if item.get("prover_execution_mode") != "easyccg_raw_text_fallback":
                continue
            problems.append(loaders[dataset].get_problem(item["id"], split=item["split"]))
    return problems


def load_existing_jsonl(path: Path) -> Dict[str, Dict[str, Any]]:
    if not path.exists():
        return {}
    records = {}
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            records[record["problem_key"]] = record
    return records


def append_jsonl(path: Path, record: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, default=str) + "\n")


async def parse_problem(problem: Any, args: argparse.Namespace, semaphore: asyncio.Semaphore) -> Dict[str, Any]:
    from kbprojection.langpro import _run_easyccg_async
    from kbprojection.local_easyccg import process_single_output
    from kbprojection.settings import get_langpro_settings

    settings = get_langpro_settings()
    sentences = list(problem.premises) + [problem.hypothesis]
    terms = []
    async with semaphore:
        for sentence in sentences:
            raw_output = await _run_easyccg_async(
                sentence,
                settings.local_easyccg_dir,
                settings.local_easyccg_spacy_model,
                args.timeout_seconds,
            )
            term = process_single_output(raw_output)
            if term is None:
                raise RuntimeError(f"Failed to convert EasyCCG output for {scoped_problem_id(problem)}")
            terms.append(term)
    return {
        "problem_key": scoped_problem_id(problem),
        "dataset": problem.dataset,
        "split": problem.split,
        "id": problem.id,
        "premises": list(problem.premises),
        "hypothesis": problem.hypothesis,
        "terms": terms,
    }


def write_corpus_files(records: Sequence[Dict[str, Any]], sen_path: Path, ccg_path: Path) -> None:
    sen_lines = [
        "% generated by scripts/analysis/build_entailment_scope_easyccg_corpus.py",
        ":- multifile sen_id/5.",
        ":- dynamic sen_id/5.",
        ":- style_check(-discontiguous).",
        "",
    ]
    ccg_lines = [
        "% generated by scripts/analysis/build_entailment_scope_easyccg_corpus.py",
        ":- op(601, xfx, (/)).",
        ":- op(601, xfx, (\\)).",
        ":- multifile ccg/2.",
        ":- dynamic ccg/2.",
        ":- style_check(-discontiguous).",
        "",
    ]

    sentence_id = 1
    for record in sorted(records, key=lambda item: item["problem_key"]):
        problem_id = prolog_problem_id(record["problem_key"])
        for premise in record["premises"]:
            sen_lines.append(
                f"sen_id({sentence_id}, {problem_id}, 'p', 'unknown', '{escape_prolog_string(premise)}')."
            )
            sentence_id += 1
        sen_lines.append(
            f"sen_id({sentence_id}, {problem_id}, 'h', 'unknown', '{escape_prolog_string(record['hypothesis'])}')."
        )
        sentence_id += 1

        base_sentence_id = sentence_id - len(record["terms"])
        for offset, term in enumerate(record["terms"]):
            ccg_lines.extend([f"ccg({base_sentence_id + offset},", term, ").", ""])

    sen_path.write_text("\n".join(sen_lines), encoding="utf-8")
    ccg_path.write_text("\n".join(ccg_lines), encoding="utf-8")


async def run_async(args: argparse.Namespace) -> int:
    from kbprojection.settings import resolve_local_langpro_root

    load_dotenv_if_present()
    extraction_path = Path(args.extraction_file).resolve()
    local_root = resolve_local_langpro_root().resolve()
    corpus_dir = local_root / "ccg_sen_d"
    corpus_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_path = Path(args.checkpoint_file).resolve() if args.checkpoint_file else PROJECT_ROOT / "scripts" / "analysis" / f"{args.corpus_prefix}_easyccg_records.jsonl"
    sen_path = corpus_dir / f"{args.corpus_prefix}_sen.pl"
    ccg_path = corpus_dir / f"{args.corpus_prefix}_eccg.pl"

    problems = load_extraction_problems(extraction_path, args.datasets)
    existing = load_existing_jsonl(checkpoint_path)
    remaining = [problem for problem in problems if scoped_problem_id(problem) not in existing]
    semaphore = asyncio.Semaphore(args.concurrency)

    progress = tqdm(total=len(remaining), desc="easyccg-corpus", unit="problem")
    async def worker(problem: Any) -> None:
        record = await parse_problem(problem, args, semaphore)
        append_jsonl(checkpoint_path, record)
        existing[record["problem_key"]] = record
        progress.update(1)
        progress.set_postfix_str(record["problem_key"][:60])

    tasks = [asyncio.create_task(worker(problem)) for problem in remaining]
    try:
        for completed in asyncio.as_completed(tasks):
            await completed
    except Exception:
        for task in tasks:
            if not task.done():
                task.cancel()
        await asyncio.gather(*tasks, return_exceptions=True)
        raise
    finally:
        progress.close()

    write_corpus_files(list(existing.values()), sen_path, ccg_path)
    print(json.dumps({
        "records": len(existing),
        "checkpoint_file": str(checkpoint_path),
        "sen_file": str(sen_path),
        "ccg_file": str(ccg_path),
    }, indent=2))
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a prepared EasyCCG corpus for selected fallback extraction items.")
    parser.add_argument("--extraction-file", default=str(DEFAULT_EXTRACTION_FILE))
    parser.add_argument("--datasets", nargs="+", default=["snli", "sick"], choices=["snli", "sick"])
    parser.add_argument("--corpus-prefix", default=DEFAULT_CORPUS_PREFIX)
    parser.add_argument("--checkpoint-file", default=None)
    parser.add_argument("--concurrency", type=int, default=2)
    parser.add_argument("--timeout-seconds", type=float, default=180.0)
    return parser.parse_args()


def main() -> int:
    return asyncio.run(run_async(parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
