import argparse
import sys
from pathlib import Path
from typing import Iterable, Iterator, List

# Requires spaCy plus the configured model when --parser is easyccg or both.
# Example:
#   uv add spacy
#   uv run python -m spacy download en_core_web_sm

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))


from kbprojection.langpro import _escape_prolog_string
from kbprojection.loaders.sick import SICKLoader
from kbprojection.loaders.snli import SNLILoader
from kbprojection.local_easyccg import process_single_output, run_easyccg
from kbprojection.settings import get_langpro_settings


CCG_HEADER = [
    ":- op(601, xfx, (/)).",
    ":- op(601, xfx, (\\)).",
    ":- multifile ccg/2, id/2.",
    ":- discontiguous ccg/2, id/2.",
    "",
]


def ensure_easyccg_dependencies(model_name: str) -> None:
    try:
        import spacy
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "EasyCCG export requires the 'spacy' package.\n"
            "Install it in this environment, for example with:\n"
            "  uv add spacy"
        ) from exc

    try:
        spacy.load(model_name, disable=["parser"])
    except OSError as exc:
        raise RuntimeError(
            f"EasyCCG export requires the spaCy model '{model_name}'.\n"
            "Install it with:\n"
            f"  uv run python -m spacy download {model_name}"
        ) from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a preparsed local LangPro corpus from SNLI or SICK."
    )
    parser.add_argument("--dataset", choices=["snli", "sick"], required=True)
    parser.add_argument("--split", required=True, help="Dataset split to export.")
    parser.add_argument(
        "--parser",
        choices=["easyccg"],
        default="easyccg",
        help="Which parser output files to generate.",
    )
    parser.add_argument(
        "--output-prefix",
        default=None,
        help="Base filename prefix inside ccg_sen_d. Defaults to a dataset-specific convention.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Directory to write *_sen.pl and parser files to. Defaults to <local_root>/ccg_sen_d.",
    )
    parser.add_argument(
        "--problem-id",
        action="append",
        dest="problem_ids",
        default=None,
        help="Specific problem id to export. Can be repeated.",
    )
    parser.add_argument(
        "--problem-id-file",
        default=None,
        help="Text file containing one problem id per line.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional limit when exporting an entire split.",
    )
    return parser.parse_args()


def default_output_prefix(dataset: str, split: str) -> str:
    if dataset == "sick":
        sick_map = {
            "train": "SICK_train",
            "dev": "SICK_trial",
            "test": "SICK_test_annotated",
        }
        if split not in sick_map:
            raise ValueError(f"Unsupported SICK split: {split}")
        return sick_map[split]

    snli_map = {
        "train": "SNLI_train",
        "dev": "SNLI_dev",
        "test": "SNLI_test",
    }
    if split not in snli_map:
        raise ValueError(f"Unsupported SNLI split: {split}")
    return snli_map[split]


def get_loader(dataset: str):
    if dataset == "snli":
        return SNLILoader()
    if dataset == "sick":
        return SICKLoader()
    raise ValueError(f"Unsupported dataset: {dataset}")


def load_requested_problems(args: argparse.Namespace):
    loader = get_loader(args.dataset)
    loader.load(splits=[args.split])

    requested_ids: List[str] = []
    if args.problem_ids:
        requested_ids.extend(args.problem_ids)
    if args.problem_id_file:
        requested_ids.extend(
            line.strip()
            for line in Path(args.problem_id_file).read_text(encoding="utf-8").splitlines()
            if line.strip()
        )

    if requested_ids:
        problems = [loader.get_problem(problem_id, split=args.split) for problem_id in requested_ids]
    else:
        problems = list(loader.iter_problems(split=args.split))

    if args.limit is not None:
        problems = problems[: args.limit]
    return problems


def iter_problem_sentences(problem) -> Iterable[tuple[str, str]]:
    for premise in problem.premises:
        yield "p", premise
    yield "h", problem.hypothesis


def iter_sen_lines(problems) -> Iterator[str]:
    yield "% generated by kbprojection/scripts/build_local_langpro_corpus.py"
    yield ""
    sentence_id = 1
    for problem_number, problem in enumerate(problems, start=1):
        yield f"% dataset problem id = {problem.id}"
        for role, sentence in iter_problem_sentences(problem):
            escaped = _escape_prolog_string(sentence)
            yield (
                f"sen_id({sentence_id}, {problem_number}, '{role}', 'unknown', '{escaped}')."
            )
            sentence_id += 1
    yield ""


def iter_easyccg_lines(problems, timeout_seconds: float) -> Iterator[str]:
    settings = get_langpro_settings()
    yield "% generated by kbprojection/scripts/build_local_langpro_corpus.py"
    yield from CCG_HEADER
    sentence_id = 1
    for problem in problems:
        for _, sentence in iter_problem_sentences(problem):
            raw_output = run_easyccg(
                sentence,
                settings.local_easyccg_dir,
                settings.local_easyccg_spacy_model,
                timeout_seconds,
            )
            term = process_single_output(raw_output)
            if term is None:
                raise RuntimeError(f"EasyCCG returned no parse for sentence: {sentence}")
            yield f"ccg({sentence_id},"
            yield term
            yield ")."
            yield ""
            sentence_id += 1


def write_lines(path: Path, lines: Iterable[str]) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        for line in lines:
            handle.write(line)
            handle.write("\n")


def main() -> int:
    args = parse_args()
    settings = get_langpro_settings()

    ensure_easyccg_dependencies(settings.local_easyccg_spacy_model)

    problems = load_requested_problems(args)
    if not problems:
        raise ValueError("No problems selected for export.")

    output_dir = Path(args.output_dir) if args.output_dir else settings.local_root / "ccg_sen_d"
    output_dir.mkdir(parents=True, exist_ok=True)

    output_prefix = args.output_prefix or default_output_prefix(args.dataset, args.split)
    timeout_seconds = settings.timeout_seconds

    sen_path = output_dir / f"{output_prefix}_sen.pl"
    write_lines(sen_path, iter_sen_lines(problems))
    print(f"Wrote {sen_path}")

    easyccg_path = output_dir / f"{output_prefix}_eccg.pl"
    write_lines(easyccg_path, iter_easyccg_lines(problems, timeout_seconds))
    print(f"Wrote {easyccg_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
